### ISSUE TITLE
No response for timezone request

### ISSUE THREAD

**Issue by ReneKl** [sntran/google_maps#39]
with valide api-key  `GoogleMaps.timezone({8.6069305,104.7196242})`   return  `{:error, `"REQUEST_DENIED"}`

**Comment by sntran** [comment]
Hi @ReneKl, sorry for the late response. Are you still experiencing the issue? We have tests for `timezone/2` and I don't see them failed with an error. You may want to check that your API key has access to Google's Timezone API.

**Comment by sntran** [comment]
I'm closing this issue. If you still have the error, feel free to reopen it.
